#!/usr/bin/env python3
"""Record, per C header, which of its functions a C program actually calls
(C SDK consumer verification plan, C5b).

The C1 audit covers every function all eleven headers declare. Only some of
them are called by a program CI runs. This script lists, for each header,
every function it declares, and which programs call it:

  consumers  net/crates/net/examples/c/*.c and examples/c/support/*.c
             (run-c-consumers.py: every lane)
  arming     net/crates/net/tests/c_abi/arming/*.c (C5's planted defects)
  skills     .claude/skills/net-event-bus/examples/*.c (the skill runner)

A function is called by a file when its name appears followed by `(` in the
file's code, outside comments and string literals. `CLM_FN(name)` entries,
the loaded-module check's list of imports, are references, not calls, and
do not count.

The record is `net/crates/net/tests/c_abi/SURFACE.md`. `--check` regenerates
it and fails if the committed file differs, so it cannot claim coverage that
no longer exists, or miss coverage that was added. The C column of the
capability matrix (C6) may claim no more than this record shows.

  python3 .github/scripts/c-surface-record.py           # rewrite the record
  python3 .github/scripts/c-surface-record.py --check   # CI: fail on drift
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, str(Path(__file__).resolve().parent))
import c_abi_model as M  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
CRATE = ROOT / "net" / "crates" / "net"
INCLUDE = CRATE / "include"
RECORD = CRATE / "tests" / "c_abi" / "SURFACE.md"
SOURCES = {
    "consumers": [CRATE / "examples" / "c", CRATE / "examples" / "c" / "support"],
    "arming": [CRATE / "tests" / "c_abi" / "arming"],
    "skills": [ROOT / ".claude" / "skills" / "net-event-bus" / "examples"],
}

_COMMENT_OR_STRING = re.compile(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\\n])*"|\'(?:\\.|[^\'\\\n])*\'', re.S)
_CLM_FN = re.compile(r"\bCLM_FN\s*\(\s*\w+\s*\)")
_CALL = re.compile(r"\b(net_\w+)\s*\(")


def code_of(text: str) -> str:
    """Source with comments, string literals and CLM_FN references removed."""
    return _CLM_FN.sub(" ", _COMMENT_OR_STRING.sub(" ", text))


def calls_in(text: str) -> set[str]:
    return set(_CALL.findall(code_of(text)))


def callers() -> dict[str, dict[str, set[str]]]:
    """function -> family -> {program stems that call it}."""
    out: dict[str, dict[str, set[str]]] = {}
    for family, dirs in SOURCES.items():
        for d in dirs:
            for src in sorted(d.glob("*.c")):
                for fn in calls_in(src.read_text(encoding="utf-8")):
                    out.setdefault(fn, {}).setdefault(family, set()).add(src.stem)
    return out


def declared() -> dict[str, list[str]]:
    """header name -> its own functions, in name order."""
    fake = M.write_fake_libc(Path(tempfile.mkdtemp()) / "fake_libc")
    out = {}
    for h in sorted(INCLUDE.glob("*.h")):
        parsed = M.parse_c_header(h, [INCLUDE], fake, M.default_cc())
        out[h.name] = sorted(parsed.functions)
    return out


def render(decl: dict[str, list[str]], calls: dict[str, dict[str, set[str]]]) -> str:
    lines = [
        "# C surface record (C5b)",
        "",
        "Generated by `.github/scripts/c-surface-record.py`; CI fails if it is",
        "stale. For each header: every function it declares, and the C programs",
        "CI runs that call it. A function with no caller is declared and audited",
        "(C1) but exercised by no C program. The C column of the capability",
        "matrix may claim no more than this. A function declared in two headers",
        "(`net.h` and `net.go.h` both declare the core surface) is listed under",
        "both.",
        "",
        "| Header | Declared | Called by a consumer | Called by any C program |",
        "| --- | ---: | ---: | ---: |",
    ]
    for h, fns in decl.items():
        cons = sum(1 for f in fns if "consumers" in calls.get(f, {}))
        anyc = sum(1 for f in fns if calls.get(f))
        lines.append(f"| `{h}` | {len(fns)} | {cons} | {anyc} |")
    for h, fns in decl.items():
        lines += ["", f"## `{h}`", ""]
        if not fns:
            lines.append("Declares no functions.")
            continue
        lines += ["| Function | Consumers | Arming | Skill examples |", "| --- | --- | --- | --- |"]
        for f in fns:
            by = calls.get(f, {})
            cells = [", ".join(sorted(by.get(k, ()))) or "–" for k in ("consumers", "arming", "skills")]
            lines.append(f"| `{f}` | " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def self_test() -> int:
    src = ('/* net_in_comment(x) */ int main(void) { static const clm_fn_t u[] = {CLM_FN(net_listed)};\n'
           'printf("net_in_string(%d)\\n", 1); net_called (a); x = net_not_a_call; // net_line(c)\n'
           'net_other(\'(\'); }\n')
    got = calls_in(src)
    ok = got == {"net_called", "net_other"}
    print(f"{'✓' if ok else '✗'} self-test: calls are found outside comments, strings and CLM_FN lists"
          + ("" if ok else f" (got {sorted(got)})"))
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed record is stale")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    text = render(declared(), callers())
    if args.check:
        have = RECORD.read_text(encoding="utf-8") if RECORD.exists() else ""
        if have != text:
            print(f"✗ {RECORD.relative_to(ROOT)} is stale; regenerate it with "
                  "python3 .github/scripts/c-surface-record.py")
            return 1
        print(f"✓ {RECORD.relative_to(ROOT)} matches the headers and the C programs")
        return 0
    RECORD.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {RECORD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
