#!/usr/bin/env python3
"""Generate the C consumer programs' fixture-case headers from the
cross-language golden vectors (C SDK consumer verification plan).

The Rust, Go, TypeScript and Python bindings all test the stateless
capability and predicate helpers against the same JSON fixtures in
`net/crates/net/tests/cross_lang_capability/`. A C program has no JSON
parser, so this script renders each fixture's cases as C data: every JSON
input as a compact string literal, every expected value as the field type
the program compares against. `examples/c/capabilities.c` runs every case.

The header is committed. `--check` regenerates it and fails on any
difference, so a fixture case added, changed or removed reaches the C
program in the same commit, or CI says so.

  python3 .github/scripts/gen-c-fixture-cases.py           # rewrite
  python3 .github/scripts/gen-c-fixture-cases.py --check   # CI
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "net" / "crates" / "net" / "tests" / "cross_lang_capability"
OUT = ROOT / "net" / "crates" / "net" / "examples" / "c" / "support" / "capability_cases.h"


def compact(value) -> str:
    """An input as the fixture gives it: no spaces, keys in their order."""
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def as_returned(value) -> str:
    """An expected result as the library returns it. The trace, debug-report
    and redaction helpers build a JSON value (serde_json's map is sorted),
    so their keys come back sorted."""
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False, sort_keys=True)


def c_str(text: str) -> str:
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + out.encode("ascii", "backslashreplace").decode("ascii").replace("\\\\u", "\\u") + '"'


def load(name: str) -> list[dict]:
    return json.loads((FIXTURES / f"{name}.json").read_text(encoding="utf-8"))["cases"]


def kinds(entries: list[dict]) -> str:
    return ",".join(e["kind"] for e in entries)


def render() -> str:
    lines = [
        "/*",
        " * capability_cases.h — GENERATED by .github/scripts/gen-c-fixture-cases.py",
        " * from the JSON fixtures in net/crates/net/tests/cross_lang_capability/. Do",
        " * not edit; CI regenerates it and fails on any difference.",
        " *",
        " * The cases every binding runs against the stateless capability and",
        " * predicate helpers, as C data for examples/c/capabilities.c.",
        " */",
        "",
        "#ifndef CU_CAPABILITY_CASES_H",
        "#define CU_CAPABILITY_CASES_H",
        "",
        "typedef struct { const char* name; const char* wire; const char* tags; const char* metadata; int expected; } cu_eval_case;",
        "typedef struct { const char* name; const char* caps; int n_errors; int n_warnings; const char* error_kinds; const char* warning_kinds; } cu_validation_case;",
        "typedef struct { const char* name; const char* wire; const char* tags; const char* metadata; int expected_result; const char* expected_trace; } cu_trace_case;",
        "typedef struct { const char* name; const char* wire; const char* contexts; unsigned long long total; unsigned long long matched; const char* clause_stats; } cu_report_case;",
        "typedef struct { const char* name; const char* report; const char* keys; const char* redacted; } cu_redact_case;",
        "typedef struct { const char* name; const char* wire; } cu_envelope_case;",
        "",
    ]

    def table(ctype: str, name: str, rows: list[str]) -> None:
        lines.append(f"static const {ctype} {name}[] = {{")
        lines.extend(f"    {{{r}}}," for r in rows)
        lines.append("};")
        lines.append(f"#define {name.upper()}_N (sizeof {name} / sizeof {name}[0])")
        lines.append("")

    table("cu_eval_case", "cu_eval_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["wire"])), c_str(compact(c["tags"])),
                   c_str(compact(c["metadata"])), "1" if c["expected"] else "0"])
        for c in load("predicate_eval")])
    table("cu_validation_case", "cu_validation_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["caps"])), str(len(c["expected_errors"])),
                   str(len(c["expected_warnings"])), c_str(kinds(c["expected_errors"])),
                   c_str(kinds(c["expected_warnings"]))])
        for c in load("capability_validation")])
    table("cu_trace_case", "cu_trace_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["wire"])), c_str(compact(c["tags"])),
                   c_str(compact(c["metadata"])), "1" if c["expected_result"] else "0",
                   c_str(as_returned(c["expected_trace"]))])
        for c in load("predicate_trace")])
    table("cu_report_case", "cu_report_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["wire"])), c_str(compact(c["contexts"])),
                   f"{c['expected_total_candidates']}ULL", f"{c['expected_matched']}ULL",
                   c_str(as_returned(c["expected_clause_stats"]))])
        for c in load("predicate_debug_report")])
    table("cu_redact_case", "cu_redact_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["report"])), c_str(compact(c["redact_keys"])),
                   c_str(as_returned(c["redacted_report"]))])
        for c in load("predicate_debug_report_redacted")])
    table("cu_envelope_case", "cu_envelope_cases", [
        ", ".join([c_str(c["name"]), c_str(compact(c["wire"]))])
        for c in load("predicate_nrpc_envelope")])

    lines.append("#endif /* CU_CAPABILITY_CASES_H */")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed header is stale")
    args = ap.parse_args()
    text = render()
    rel = OUT.relative_to(ROOT).as_posix()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"✗ {rel} is stale; regenerate it with python3 .github/scripts/gen-c-fixture-cases.py")
            return 1
        print(f"✓ {rel} matches the cross-language fixtures")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
