//! Layout of every struct the C headers publish with a body, measured by
//! rustc and compared with the reviewed fixture
//! `net/crates/net/tests/c_abi/layout.json`.
//!
//! C SDK consumer verification, C1 check 4
//! (docs/internal/plans/C_SDK_CONSUMER_VERIFICATION_PLAN.md). The fixture is
//! where the two compilers meet: this test requires the Rust `#[repr(C)]`
//! structs to have exactly its size, alignment and field offsets, and
//! `.github/scripts/check-c-abi.py` compiles the same numbers as C
//! `_Static_assert`s against the shipped headers. Either side drifting fails
//! one of them.
//!
//! The table below is generated by
//! `check-c-abi.py --bundle <bundle> --emit-layout-table`, which pairs each C
//! struct with its Rust counterpart and the fields in order. The audit also
//! requires the fixture to cover every published struct, so a struct added to
//! a header without a row here fails there.
//!
//! To regenerate the fixture after an intended layout change:
//!
//! ```text
//! NET_ABI_LAYOUT_WRITE=1 cargo test --release -p net-ffi --test abi_layout
//! ```
//!
//! The fixture records a 64-bit target's sizes and offsets (pointers and
//! `size_t` are 8 bytes), the only width the C SDK is built and audited for,
//! so the test compiles only there: on a 32-bit target it would fail against
//! headers and code that are consistent, and regenerating would overwrite
//! the 64-bit fixture.
#![cfg(target_pointer_width = "64")]

use std::collections::BTreeMap;
use std::mem::{align_of, offset_of, size_of};
use std::path::PathBuf;

struct Measured {
    c_name: &'static str,
    rust_path: String,
    size: usize,
    align: usize,
    /// (C field, Rust field, offset)
    fields: Vec<(&'static str, &'static str, usize)>,
}

macro_rules! measure {
    ($c:literal => $ty:path { $($cf:literal : $rf:ident),* $(,)? }) => {
        Measured {
            c_name: $c,
            // `stringify!` of a path may space its `::` separators.
            rust_path: stringify!($ty).replace(' ', ""),
            size: size_of::<$ty>(),
            align: align_of::<$ty>(),
            fields: vec![$(($cf, stringify!($rf), offset_of!($ty, $rf))),*],
        }
    };
}

fn measured() -> Vec<Measured> {
    vec![
        measure!("NetDeckChainCommit" => net_deck::NetDeckChainCommit { "commit_id": commit_id, "operator_id": operator_id, "event_kind": event_kind, "committed_at_ms": committed_at_ms }),
        measure!("NetDeckFailureRecord" => net_deck::NetDeckFailureRecord { "seq": seq, "source": source, "reason": reason, "recorded_at_ms": recorded_at_ms }),
        measure!("NetDeckLogFilter" => net_deck::NetDeckLogFilter { "min_level_present": min_level_present, "min_level": min_level, "daemon_id_present": daemon_id_present, "daemon_id": daemon_id, "node_id_present": node_id_present, "node_id": node_id, "since_seq_present": since_seq_present, "since_seq": since_seq }),
        measure!("NetDeckLogRecord" => net_deck::NetDeckLogRecord { "seq": seq, "ts_ms": ts_ms, "level": level, "daemon_id_present": daemon_id_present, "daemon_id": daemon_id, "node_id_present": node_id_present, "node_id": node_id, "message": message }),
        measure!("NetDeckOperatorSignature" => net_deck::NetDeckOperatorSignature { "operator_id": operator_id, "signature_ptr": signature_ptr, "signature_len": signature_len }),
        measure!("NetDeckStatusSummary" => net_deck::NetDeckStatusSummary { "peers": peers, "daemons": daemons, "replica_chains": replica_chains, "avoid_list_entries": avoid_list_entries, "recently_emitted_count": recently_emitted_count, "recent_failure_count": recent_failure_count, "admin_audit_ring_depth": admin_audit_ring_depth, "freeze_remaining_present": freeze_remaining_present, "freeze_remaining_ms": freeze_remaining_ms, "local_maintenance_active": local_maintenance_active }),
        measure!("NetMeshOsDaemonControl" => net_meshos::NetMeshOsDaemonControl { "kind": kind, "grace_period_ms": grace_period_ms, "level": level }),
        measure!("NetMeshOsDaemonVtable" => net_meshos::NetMeshOsDaemonVtable { "process": process, "snapshot": snapshot, "restore": restore, "on_control": on_control, "health": health, "saturation": saturation }),
        measure!("RpcCallEventC" => net_rpc::RpcCallEventC { "caller": caller, "callee": callee, "method_ptr": method_ptr, "method_len": method_len, "latency_ms": latency_ms, "status_kind": status_kind, "status_message_ptr": status_message_ptr, "status_message_len": status_message_len, "request_bytes": request_bytes, "response_bytes": response_bytes, "direction": direction, "ts_unix_ms": ts_unix_ms }),
        measure!("net_blob_adapter_vtable_t" => net::ffi::blob::NetBlobAdapterVtable { "store": store, "fetch": fetch, "fetch_range": fetch_range, "exists": exists, "free_buffer": free_buffer }),
        measure!("net_org_caller_t" => net_org::NetOrgCaller { "caller": caller, "acting_org": acting_org, "provider_org": provider_org, "provider": provider, "capability": capability }),
        measure!("net_poll_result_t" => net::ffi::NetPollResult { "events": events, "count": count, "next_id": next_id, "has_more": has_more }),
        measure!("net_receipt_t" => net::ffi::NetReceipt { "shard_id": shard_id, "timestamp": timestamp }),
        measure!("net_rpc_header_t" => net_rpc::NetRpcHeader { "name_ptr": name_ptr, "name_len": name_len, "value_ptr": value_ptr, "value_len": value_len }),
        measure!("net_stats_t" => net::ffi::NetStats { "events_ingested": events_ingested, "events_dropped": events_dropped, "batches_dispatched": batches_dispatched }),
        measure!("net_subnet_path_t" => net_org::NetSubnetPath { "depth": depth, "levels": levels }),
        measure!("net_traversal_stats_v2_t" => net::ffi::mesh::NetTraversalStatsV2 { "punches_attempted": punches_attempted, "punches_succeeded": punches_succeeded, "punches_failed": punches_failed, "relay_fallbacks": relay_fallbacks, "punch_timeouts": punch_timeouts, "punch_rejections": punch_rejections, "rendezvous_no_relay": rendezvous_no_relay, "upgrades_attempted": upgrades_attempted, "upgrades_succeeded": upgrades_succeeded, "upgrades_deferred_busy": upgrades_deferred_busy, "port_mapping_renewals": port_mapping_renewals, "port_mapping_active": port_mapping_active, "port_mapping_external": port_mapping_external }),
        measure!("net_workflow_status_counts_t" => net::ffi::cortex::NetWorkflowStatusCounts { "submitted": submitted, "running": running, "waiting": waiting, "blocked": blocked, "done": done, "failed": failed }),
        measure!("NetDeckDaemonCounts" => net_deck::NetDeckDaemonCounts { "running": running, "starting": starting, "stopping": stopping, "stopped": stopped, "backing_off": backing_off, "crash_looping": crash_looping }),
        measure!("NetDeckPeerCounts" => net_deck::NetDeckPeerCounts { "healthy": healthy, "degraded": degraded, "unreachable": unreachable, "unknown": unknown }),
        measure!("net_event_t" => net::ffi::NetEvent { "id": id, "id_len": id_len, "raw": raw, "raw_len": raw_len, "insertion_ts": insertion_ts, "shard_id": shard_id }),
    ]
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../tests/c_abi/layout.json")
}

fn as_json(all: &[Measured]) -> serde_json::Value {
    let mut structs = BTreeMap::new();
    for m in all {
        let fields: Vec<serde_json::Value> = m
            .fields
            .iter()
            .map(|(c, r, off)| serde_json::json!([c, r, off]))
            .collect();
        structs.insert(
            m.c_name.to_string(),
            serde_json::json!({
                "rust": m.rust_path,
                "size": m.size,
                "align": m.align,
                "fields": fields,
            }),
        );
    }
    serde_json::json!({
        "comment": "rustc layout of every struct the C headers publish; written by \
                    bindings/go/net-ffi/tests/abi_layout.rs, compiled as C assertions by \
                    .github/scripts/check-c-abi.py",
        "structs": structs,
    })
}

#[test]
fn published_structs_have_the_fixture_layout() {
    let all = measured();
    assert!(!all.is_empty(), "the measure! table is empty");
    let measured = as_json(&all);
    let path = fixture_path();
    if std::env::var_os("NET_ABI_LAYOUT_WRITE").is_some() {
        let text = serde_json::to_string_pretty(&measured).expect("serialise") + "\n";
        std::fs::write(&path, text).expect("write the layout fixture");
        return;
    }
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let fixture: serde_json::Value = serde_json::from_str(&text).expect("parse the layout fixture");
    assert_eq!(
        fixture["structs"],
        measured["structs"],
        "rustc's layout differs from {}. If the change is intended, regenerate it with \
         NET_ABI_LAYOUT_WRITE=1 and review the diff; the C assertions in check-c-abi.py \
         then hold the headers to the same numbers.\nmeasured:\n{}",
        path.display(),
        serde_json::to_string_pretty(&measured["structs"]).unwrap_or_default()
    );
}
