//! The `cross_lang_wire` vectors, as constants inside this package.
//!
//! **Packaging, not convenience.** The wasm test target replays
//! these fixtures *inside wasm* — that is a Stage 5 exit criterion —
//! and `include_str!` reaching outside the package compiles in the
//! repository and then fails in an unpacked `cargo package` tarball,
//! which is exactly the build a publish produces. `net-mesh-wire`
//! hit this first and answered it the same way
//! ([`net_wire::test_vectors`]); this is the leaf's copy of that
//! answer.
//!
//! The repository originals under
//! `net/crates/net/tests/cross_lang_wire/` are what a Go /
//! TypeScript / Python consumer reads, and
//! `tests/fixture_parity.rs` asserts every constant here is
//! byte-identical to its original. Two copies that cannot drift.
//!
//! Behind the `test-vectors` feature: a shipped browser bundle must
//! not carry test data.

/// `net_header.json` — the 68-byte packet header.
pub const NET_HEADER: &str = include_str!("test_vectors/net_header.json");

/// `routing_header.json` — the 18-byte routing envelope.
pub const ROUTING_HEADER: &str = include_str!("test_vectors/routing_header.json");

/// `event_frame.json` — the length-prefixed event framing.
pub const EVENT_FRAME: &str = include_str!("test_vectors/event_frame.json");

/// `nack_payload.json` — the reliable-stream NACK.
pub const NACK_PAYLOAD: &str = include_str!("test_vectors/nack_payload.json");

/// `stream_window.json` — the `0x0B00` credit grant.
pub const STREAM_WINDOW: &str = include_str!("test_vectors/stream_window.json");

/// `capability_announcement.json` — the pre-Stage-4 announcement.
pub const CAPABILITY_ANNOUNCEMENT: &str = include_str!("test_vectors/capability_announcement.json");

/// `capability_announcement_rtc.json` — the announcement with the
/// three Stage 4a browser-leaf fields.
pub const CAPABILITY_ANNOUNCEMENT_RTC: &str =
    include_str!("test_vectors/capability_announcement_rtc.json");

/// `capability_announcement_leaf.json` — a leaf's own announcement,
/// generated by this crate and pinned from the core side too.
pub const CAPABILITY_ANNOUNCEMENT_LEAF: &str =
    include_str!("test_vectors/capability_announcement_leaf.json");

/// `nrpc_frame.json` — one nRPC REQUEST frame, generated by this
/// crate's client codec and pinned from the core side too.
pub const NRPC_FRAME: &str = include_str!("test_vectors/nrpc_frame.json");

/// `enroll_exchange.json` — the device-side enrollment objects
/// (invite, signed join request, both outcome shapes), generated by
/// this crate's encoder.
pub const ENROLL_EXCHANGE: &str = include_str!("test_vectors/enroll_exchange.json");

/// Every vector with its repository filename, for the parity test.
pub const ALL: [(&str, &str); 10] = [
    ("net_header.json", NET_HEADER),
    ("routing_header.json", ROUTING_HEADER),
    ("event_frame.json", EVENT_FRAME),
    ("nack_payload.json", NACK_PAYLOAD),
    ("stream_window.json", STREAM_WINDOW),
    ("capability_announcement.json", CAPABILITY_ANNOUNCEMENT),
    (
        "capability_announcement_rtc.json",
        CAPABILITY_ANNOUNCEMENT_RTC,
    ),
    (
        "capability_announcement_leaf.json",
        CAPABILITY_ANNOUNCEMENT_LEAF,
    ),
    ("nrpc_frame.json", NRPC_FRAME),
    ("enroll_exchange.json", ENROLL_EXCHANGE),
];
