/**
 * MeshDB SDK wrapper.
 *
 * Re-exports the MeshDB query layer from `@ai2070/net` (the napi
 * binding) so `@ai2070/net-sdk` consumers can stay on the
 * ergonomic SDK module instead of dropping into the napi package.
 * Also imports the AsyncIterable shim from `@ai2070/net/meshdb`
 * once, so `for await (const row of stream)` works without the
 * consumer having to remember the side-effect import.
 *
 * @example
 * ```typescript
 * import {
 *   InMemoryChainReader,
 *   MeshQuery,
 *   MeshQueryRunner,
 *   QueryBuilder,
 * } from '@ai2070/net-sdk/meshdb';
 *
 * const reader = new InMemoryChainReader();
 * // …populate reader…
 * const runner = new MeshQueryRunner(reader);
 *
 * const query = new QueryBuilder().fromOrigin(0n).build();
 * const stream = await runner.execute(query);
 * for await (const row of stream) {
 *   console.log(row.seq, row.payload);
 * }
 * ```
 */

/**
 * Result of {@link parseMeshDbErrorKind} — the structured error kind
 * extracted from a MeshDB error envelope, plus the human-readable
 * message stripped of the `<<meshdb-kind:...>>` prefix.
 */
export interface ParsedMeshDbError {
  kind: string;
  message: string;
}

/**
 * Pull the structured error kind out of a MeshDB error message.
 * The substrate wraps every typed error as
 * `<<meshdb-kind:KIND>>MESSAGE`; this helper splits the two halves so
 * callers can dispatch programmatically. Returns `null` when the
 * envelope is absent (forward-compatibility — unknown error shapes
 * pass through unchanged).
 *
 * Mirrors the napi-side helper at `@ai2070/net/meshdb` so consumers
 * don't have to reach across packages for the parser.
 */
export function parseMeshDbErrorKind(raw: string): ParsedMeshDbError | null {
  const marker = '<<meshdb-kind:';
  const start = raw.indexOf(marker);
  if (start === -1) return null;
  const end = raw.indexOf('>>', start + marker.length);
  if (end === -1) return null;
  const kind = raw.slice(start + marker.length, end);
  const message = raw.slice(end + 2);
  return { kind, message };
}

/**
 * Note on AsyncIterable: the napi-side `MeshQueryStream` ships with a
 * separate side-effect module (`@ai2070/net/meshdb`) that augments
 * the prototype with `[Symbol.asyncIterator]`. To use
 * `for await (const row of stream)` syntax, import it once at
 * startup:
 *
 * ```typescript
 * import '@ai2070/net/meshdb';
 * import { MeshQueryRunner } from '@ai2070/net-sdk/meshdb';
 * ```
 *
 * Without the side-effect import the stream still works via the
 * imperative `next()` / `toArray()` methods.
 */

// Class re-exports — generated by napi-rs; identity-stable across
// imports of the same loaded module.
export {
  InMemoryChainReader,
  MeshQuery,
  MeshQueryRunner,
  MeshQueryStream,
  QueryBuilder,
} from '@ai2070/net';

// Interface / type re-exports — wire shapes the napi emits / consumes.
// `Predicate` is re-exported as `MeshDbPredicate` to disambiguate from
// the capability-system Predicate exported elsewhere in the SDK.
export type {
  AggregateResult,
  CachePolicy,
  ExecuteOptions,
  GroupKey,
  JoinedRow,
  LineageEntry,
  Predicate as MeshDbPredicate,
  ResultRow,
  WindowBoundary,
} from '@ai2070/net';

/**
 * Disposable-friendly wrapper around `MeshQueryRunner` for callers
 * who want explicit lifetime management via the TC39
 * `using`/`Symbol.dispose` protocol. The underlying runner has no
 * native close; this wrapper exists so consumers can pair it with
 * other Disposable resources in a single `using` chain.
 *
 * @example
 * ```typescript
 * using runner = new DisposableMeshQueryRunner(reader);
 * const stream = await runner.runner.execute(query);
 * // runner is released when the enclosing scope exits.
 * ```
 */
export class DisposableMeshQueryRunner {
  // Lazily-typed because the napi runner has no exported instance shape
  // we can name without importing the value (and the value import is
  // already covered above).
  readonly runner: import('@ai2070/net').MeshQueryRunner;

  constructor(reader: import('@ai2070/net').InMemoryChainReader) {
    const Runner = require('@ai2070/net').MeshQueryRunner;
    this.runner = new Runner(reader);
  }

  [Symbol.dispose](): void {
    // Runner has no native close — drop the reference so GC can
    // collect it deterministically once the using-block exits.
    // The reader retains its own Arc clone of the chain.
    (this as { runner: unknown }).runner = undefined;
  }
}
