// SPDX-License-Identifier: MIT OR Apache-2.0
//! Workspace-internal storage for the SDK enrollment ledger under construction.
//! Fixed filenames, exclusive lifetime ownership, bounded secret reads and phased
//! durable replacement. This stores opaque bytes, not verified credentials.
//! The SDK must validate schema/issuer/transitions before serving any result.
//!
//! Dedicated trusted directory only: as with org authority, hostile mutation by
//! the same OS account (or privileged administrators) is outside this boundary.
//! Supported platforms are Unix and Windows; others refuse. No debug formatter
//! exposes payloads. Returned bytes are secret-bearing and caller-owned.

use super::{
    org_authority,
    org_revocation::{write_atomic_phased, WritePhase},
};
use std::{
    fs::File,
    io::Read,
    path::{Path, PathBuf},
};

/// Hard allocation/write ceiling for the opaque snapshot (64 MiB).
pub const MAX_SNAPSHOT_BYTES: usize = 64 * 1024 * 1024;
const SNAPSHOT: &str = "enrollment.snapshot";
const LOCK: &str = "enrollment.lock";

/// Payload-free failures. Uncertainty is not a successful commit or a rollback.
#[derive(Debug, thiserror::Error)]
pub enum StorageError {
    /// Failed directory, file, ownership or ACL validation.
    #[error("enrollment storage security validation failed")]
    Security,
    /// Initialization never overwrites an existing directory.
    #[error("enrollment storage directory already exists")]
    AlreadyExists,
    /// Another service owns the stable sidecar lock.
    #[error("enrollment storage is already owned")]
    Busy,
    /// Storage operation failed before publication; source contains no payload.
    #[error("enrollment storage I/O: {0}")]
    Io(#[from] std::io::Error),
    /// Allocation/write limit exceeded.
    #[error("enrollment snapshot exceeds its size limit")]
    TooLarge,
    /// Rename happened, but durable publication is not established.
    #[error("enrollment storage durability uncertain; close and reopen before use")]
    Uncertain,
}

/// Exclusive, non-cloneable owner of one fixed snapshot. Blocking filesystem I/O.
pub struct EnrollmentStorage {
    dir: PathBuf,
    _lock: File,
    uncertain: bool,
}

impl EnrollmentStorage {
    /// Initialize a new dedicated directory. Refuses existing paths, even empty.
    /// The parent must already exist. Failed initialization may leave a protected partial directory; never reset
    /// it automatically. No key material is generated by this operation.
    pub fn create(dir: &Path, initial: &[u8]) -> Result<Self, StorageError> {
        if initial.len() > MAX_SNAPSHOT_BYTES {
            return Err(StorageError::TooLarge);
        }
        let dir = org_authority::normalize_authority_dir(dir)?;
        match std::fs::symlink_metadata(&dir) {
            Ok(_) => return Err(StorageError::AlreadyExists),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
        let parent = dir.parent().ok_or(StorageError::Security)?;
        if !std::fs::metadata(parent)?.is_dir() {
            return Err(StorageError::Security);
        }
        secure_dir(&dir)?;
        // Persist the new directory entry as well as the later snapshot rename.
        // Do not create a chain of unflushed intermediate directories here.
        #[cfg(unix)]
        File::open(parent)?.sync_all()?;
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.mode(0o600);
        }
        opts.open(dir.join(LOCK))?.sync_all()?;
        let lock = locked(&dir)?;
        let mut owner = Self {
            dir,
            _lock: lock,
            uncertain: false,
        };
        owner.replace(initial)?;
        Ok(owner)
    }

    /// Open existing protected state, never creating missing state/lock files.
    /// Re-persist the bounded existing snapshot under the lifetime lock to
    /// establish durability before use after an interrupted publication. This
    /// validates storage only; the SDK must validate the snapshot's meaning.
    pub fn open(dir: &Path) -> Result<Self, StorageError> {
        let dir = org_authority::normalize_authority_dir(dir)?;
        if !std::fs::symlink_metadata(&dir)?.is_dir() {
            return Err(StorageError::Security);
        }
        secure_dir(&dir)?;
        let lock = locked(&dir)?;
        let mut owner = Self {
            dir,
            _lock: lock,
            uncertain: false,
        };
        let bytes = owner.read()?;
        owner.replace(&bytes)?;
        Ok(owner)
    }

    /// Read a bounded snapshot through a checked handle; fail closed if uncertain.
    pub fn read(&self) -> Result<Vec<u8>, StorageError> {
        if self.uncertain {
            return Err(StorageError::Uncertain);
        }
        let file = checked_file(&self.dir.join(SNAPSHOT))?;
        if file.metadata()?.len() > MAX_SNAPSHOT_BYTES as u64 {
            return Err(StorageError::TooLarge);
        }
        let mut bytes = Vec::new();
        file.take(MAX_SNAPSHOT_BYTES as u64 + 1)
            .read_to_end(&mut bytes)?;
        if bytes.len() > MAX_SNAPSHOT_BYTES {
            return Err(StorageError::TooLarge);
        }
        Ok(bytes)
    }

    /// Durably replace the fixed snapshot. No caller-controlled filename and no
    /// in-memory success publication before the platform durability boundary.
    pub fn replace(&mut self, bytes: &[u8]) -> Result<(), StorageError> {
        self.replace_using(bytes, write_atomic_phased)
    }

    fn replace_using(
        &mut self,
        bytes: &[u8],
        write: impl FnOnce(&Path, &[u8]) -> Result<(), WritePhase>,
    ) -> Result<(), StorageError> {
        if self.uncertain {
            return Err(StorageError::Uncertain);
        }
        if bytes.len() > MAX_SNAPSHOT_BYTES {
            return Err(StorageError::TooLarge);
        }
        secure_dir(&self.dir)?;
        // Initialization alone has no snapshot yet. Never repair an insecure
        // existing file by replacing it with a fresh protected inode.
        let path = self.dir.join(SNAPSHOT);
        match std::fs::symlink_metadata(&path) {
            Ok(_) => {
                checked_file(&path)?;
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
        match write(&path, bytes) {
            Ok(()) => Ok(()),
            Err(WritePhase::PreRename(_)) => Err(StorageError::Io(std::io::Error::other(
                "snapshot replacement failed before publication",
            ))),
            Err(WritePhase::PostRename(_)) => {
                self.uncertain = true;
                Err(StorageError::Uncertain)
            }
        }
    }
}

fn secure_dir(dir: &Path) -> Result<(), StorageError> {
    if !cfg!(any(unix, windows)) {
        return Err(StorageError::Security);
    }
    org_authority::ensure_secure_authority_dir(dir).map_err(|_| StorageError::Security)
}

/// Open `path` read-only under the crate's shared planted-inode policy
/// (`org_revocation::open_regular_policy` — no-follow, `O_NONBLOCK`, type
/// check on the OPENED descriptor), then the owner and permission checks
/// below. A planted non-regular inode is a [`StorageError::Security`]
/// refusal on every platform — never a hang and never an `Io` the caller
/// could mistake for missing state (review finding 6).
fn checked_file(path: &Path) -> Result<File, StorageError> {
    let mut opts = std::fs::OpenOptions::new();
    opts.read(true);
    let file = match super::org_revocation::open_regular_policy(path, &mut opts) {
        Ok(file) => file,
        Err(e) if e.kind() == std::io::ErrorKind::InvalidInput => {
            // The policy refuses planted inodes (symlink/FIFO/directory):
            // fail closed as `Security`, matching every other planted
            // inode shape in this module.
            return Err(StorageError::Security);
        }
        Err(e) => {
            // The open itself failed before any check could run (Windows
            // refuses to open a directory at all). A non-regular inode is
            // still a policy refusal; anything else stays a plain IO
            // failure. Fail-closed either way.
            if let Ok(meta) = std::fs::symlink_metadata(path) {
                if !meta.is_file() {
                    return Err(StorageError::Security);
                }
            }
            return Err(StorageError::Io(e));
        }
    };
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        let meta = file.metadata()?;
        // SAFETY: geteuid has no preconditions and returns the effective UID.
        let uid = unsafe { libc::geteuid() };
        if meta.uid() != uid || meta.mode() & 0o077 != 0 || meta.nlink() != 1 {
            return Err(StorageError::Security);
        }
    }
    #[cfg(windows)]
    {
        org_authority::validate_audience_file_acl_handle(&file, path)
            .map_err(|_| StorageError::Security)?;
        if super::org_revocation::windows_file_identity(&file)?.2 != 1 {
            return Err(StorageError::Security);
        }
    }
    Ok(file)
}

fn locked(dir: &Path) -> Result<File, StorageError> {
    let file = checked_file(&dir.join(LOCK))?;
    file.try_lock().map_err(|e| match e {
        std::fs::TryLockError::WouldBlock => StorageError::Busy,
        std::fs::TryLockError::Error(e) => StorageError::Io(e),
    })?;
    Ok(file)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exclusive_owner_and_restart_preserve_exact_bytes() {
        const CHILD_PATH: &str = "NET_ENROLLMENT_STORAGE_LOCK_CHILD";
        if let Some(dir) = std::env::var_os(CHILD_PATH) {
            assert!(matches!(
                EnrollmentStorage::open(Path::new(&dir)),
                Err(StorageError::Busy)
            ));
            std::fs::write(Path::new(&dir).join("child-observed-busy"), b"").unwrap();
            return;
        }
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let mut owner = EnrollmentStorage::create(&dir, b"first").unwrap();
        assert!(matches!(
            EnrollmentStorage::open(&dir),
            Err(StorageError::Busy)
        ));
        let name = format!(
            "{}::exclusive_owner_and_restart_preserve_exact_bytes",
            module_path!()
        );
        let name = name.split_once("::").unwrap().1;
        let mut child = std::process::Command::new(std::env::current_exe().unwrap())
            .args(["--exact", name])
            .env(CHILD_PATH, &dir)
            .spawn()
            .unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
        loop {
            if let Some(status) = child.try_wait().unwrap() {
                assert!(status.success());
                break;
            }
            if std::time::Instant::now() >= deadline {
                child.kill().unwrap();
                child.wait().unwrap();
                panic!("competing owner hung");
            }
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
        assert!(
            dir.join("child-observed-busy").exists(),
            "child witness must actually run"
        );
        owner.replace(b"second").unwrap();
        assert_eq!(owner.read().unwrap(), b"second");
        drop(owner);
        // On Unix the lock is `flock`, owned by the open file description. A
        // child forked by ANOTHER test thread shares that description until
        // its exec closes the (CLOEXEC) descriptor, so in this multithreaded
        // test binary the lock can briefly outlive `drop`. Retry `Busy`
        // within a bound; any other error, or a lock that never frees, fails.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        let reopened = loop {
            match EnrollmentStorage::open(&dir) {
                Err(StorageError::Busy) if std::time::Instant::now() < deadline => {
                    std::thread::sleep(std::time::Duration::from_millis(10));
                }
                other => break other.unwrap(),
            }
        };
        assert_eq!(reopened.read().unwrap(), b"second");
        assert!(matches!(
            EnrollmentStorage::create(&dir, b"reset"),
            Err(StorageError::AlreadyExists)
        ));
    }

    #[test]
    fn missing_state_is_not_initialized_by_open() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("missing");
        assert!(EnrollmentStorage::open(&dir).is_err());
        assert!(!dir.exists());
        let owner = EnrollmentStorage::create(&dir, b"first").unwrap();
        drop(owner);
        std::fs::remove_file(dir.join(SNAPSHOT)).unwrap();
        assert!(EnrollmentStorage::open(&dir).is_err());
        assert!(!dir.join(SNAPSHOT).exists());
    }

    #[test]
    fn phase_failures_preserve_or_fence_reads_and_writes() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let mut owner = EnrollmentStorage::create(&dir, b"first").unwrap();
        assert!(owner
            .replace_using(b"second", |_, _| Err(WritePhase::PreRename(
                "injected".into()
            )))
            .is_err());
        assert_eq!(owner.read().unwrap(), b"first");
        assert!(matches!(
            owner.replace_using(b"second", |path, bytes| {
                write_atomic_phased(path, bytes)?;
                Err(WritePhase::PostRename("injected".into()))
            }),
            Err(StorageError::Uncertain)
        ));
        assert!(matches!(owner.read(), Err(StorageError::Uncertain)));
        assert!(matches!(
            owner.replace(b"third"),
            Err(StorageError::Uncertain)
        ));
        drop(owner);
        assert_eq!(
            EnrollmentStorage::open(&dir).unwrap().read().unwrap(),
            b"second"
        );
    }

    #[test]
    fn hardlinked_snapshot_is_refused() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let owner = EnrollmentStorage::create(&dir, b"secret").unwrap();
        std::fs::hard_link(dir.join(SNAPSHOT), dir.join("alias")).unwrap();
        assert!(owner.read().is_err());
    }

    #[test]
    fn oversized_snapshot_is_refused_before_allocation() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let owner = EnrollmentStorage::create(&dir, b"small").unwrap();
        std::fs::OpenOptions::new()
            .write(true)
            .open(dir.join(SNAPSHOT))
            .unwrap()
            .set_len(MAX_SNAPSHOT_BYTES as u64 + 1)
            .unwrap();
        assert!(matches!(owner.read(), Err(StorageError::TooLarge)));
    }

    #[test]
    fn planted_directory_is_refused() {
        // A directory where a file inode belongs is refused as `Security`
        // — the same fail-closed class as the hardlink, symlink and
        // permissive-mode refusals — by the type check on the OPENED
        // descriptor (or its classification when the open itself refuses,
        // as on Windows). Runnable on every platform, unlike the FIFO
        // case below, so it carries the refusal-class claim locally.
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let mut owner = EnrollmentStorage::create(&dir, b"secret").unwrap();
        // Positive control: healthy state works, so the refusals below
        // are the planted inode and not a broken setup.
        assert_eq!(owner.read().unwrap(), b"secret");
        let snapshot = dir.join(SNAPSHOT);
        std::fs::remove_file(&snapshot).unwrap();
        std::fs::create_dir(&snapshot).unwrap();
        let res = owner.read();
        assert!(
            matches!(res, Err(StorageError::Security)),
            "planted snapshot directory must be refused as Security, got {res:?}"
        );
        let res = owner.replace(b"next");
        assert!(
            matches!(res, Err(StorageError::Security)),
            "replace must refuse a planted snapshot directory as Security, got {res:?}"
        );
        drop(owner);
        let lock = dir.join(LOCK);
        std::fs::remove_file(&lock).unwrap();
        std::fs::create_dir(&lock).unwrap();
        let err = EnrollmentStorage::open(&dir).err();
        assert!(
            matches!(err, Some(StorageError::Security)),
            "planted lock directory must be refused as Security, got {err:?}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn fifo_lock_and_snapshot_are_refused() {
        // Review finding 6: the planted FIFO is the one tampering shape
        // that used to become a process hang instead of a refusal —
        // `open(2)` on a FIFO without `O_NONBLOCK` parks until a writer
        // appears. Each operation runs under a watchdog so the inverse
        // (blocking open) fails with the hang NAMED instead of wedging
        // the harness. `mkfifo -m 0600` keeps the inode owned, private
        // and single-link, so the type check is the only refusal path
        // that can fire. Never executed on non-Unix hosts; CI-only.
        fn refusing<T: Send + 'static>(what: &str, op: impl FnOnce() -> T + Send + 'static) -> T {
            let (tx, rx) = std::sync::mpsc::channel();
            std::thread::spawn(move || {
                let _ = tx.send(op());
            });
            match rx.recv_timeout(std::time::Duration::from_secs(10)) {
                Ok(v) => v,
                Err(_) => {
                    panic!("{what} parked instead of refusing: planted FIFO blocked the open")
                }
            }
        }
        fn mkfifo(path: &Path) {
            let ok = std::process::Command::new("mkfifo")
                .args(["-m", "0600"])
                .arg(path)
                .status()
                .expect("mkfifo must run on the unix witness host");
            assert!(
                ok.success(),
                "mkfifo must plant a real FIFO for this witness"
            );
        }

        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let owner = EnrollmentStorage::create(&dir, b"secret").unwrap();
        assert_eq!(owner.read().unwrap(), b"secret");
        let snapshot = dir.join(SNAPSHOT);
        std::fs::remove_file(&snapshot).unwrap();
        mkfifo(&snapshot);
        let (mut owner, res) = refusing("read() with a FIFO snapshot", move || {
            let res = owner.read();
            (owner, res)
        });
        assert!(
            matches!(res, Err(StorageError::Security)),
            "planted FIFO snapshot must be refused as Security, got {res:?}"
        );
        let (owner, res) = refusing("replace() with a FIFO snapshot", move || {
            let res = owner.replace(b"next");
            (owner, res)
        });
        assert!(
            matches!(res, Err(StorageError::Security)),
            "replace must refuse a planted FIFO snapshot as Security, got {res:?}"
        );
        drop(owner);
        let lock = dir.join(LOCK);
        std::fs::remove_file(&lock).unwrap();
        mkfifo(&lock);
        let res = refusing("open() with a FIFO lock", move || {
            EnrollmentStorage::open(&dir).map(|_| ()).err()
        });
        assert!(
            matches!(res, Some(StorageError::Security)),
            "planted FIFO lock must be refused as Security, got {res:?}"
        );
    }

    #[cfg(windows)]
    #[test]
    fn explicit_world_read_acl_is_refused_on_windows() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let mut owner = EnrollmentStorage::create(&dir, b"first secret").unwrap();
        owner.replace(b"replacement secret").unwrap();
        assert_eq!(owner.read().unwrap(), b"replacement secret");
        let status = std::process::Command::new("icacls")
            .arg(dir.join(SNAPSHOT))
            .args(["/grant", "*S-1-1-0:(R)"])
            .output()
            .unwrap()
            .status;
        assert!(status.success());
        assert!(matches!(owner.read(), Err(StorageError::Security)));
        assert!(matches!(
            owner.replace(b"repair"),
            Err(StorageError::Security)
        ));
        drop(owner);
        assert!(matches!(
            EnrollmentStorage::open(&dir),
            Err(StorageError::Security)
        ));
    }

    #[cfg(unix)]
    #[test]
    fn permissive_file_and_symlink_are_refused() {
        use std::os::unix::fs::{symlink, PermissionsExt};
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("ledger");
        let owner = EnrollmentStorage::create(&dir, b"secret").unwrap();
        let path = dir.join(SNAPSHOT);
        assert_eq!(
            std::fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(owner.read().is_err());
        std::fs::remove_file(&path).unwrap();
        symlink(dir.join(LOCK), &path).unwrap();
        assert!(owner.read().is_err());
    }
}
