//! The SDK side of the `cross_lang_wire` enroll pin (MR#126).
//!
//! `net/crates/net/tests/cross_lang_wire/enroll_exchange.json` is the
//! shared cross-language golden vector for the enrollment exchange's
//! device-side wire objects — generated by net-mesh-leaf's mirror
//! encoder and pinned byte-for-byte against that mirror by
//! `leaf/tests/fixture_parity.rs`. Until this file existed the pin was
//! one-directional: the fixture could drift from the production codec
//! (`InviteToken` / `JoinRequest` / `JoinOutcome` in
//! `sdk/src/enrollment.rs`) without any test failing. The fixture's
//! own `description` names this test as the missing half:
//! `JoinRequest::from_bytes` accepting `join_request_hex` with
//! `verify_self_signature()` passing over it, and `InviteToken::from_bytes`
//! accepting `invite_hex`.
//!
//! Three jobs, mirroring `leaf/tests/fixture_parity.rs`'s shape:
//!
//! 1. **Every fixture object the registry names is asserted.** A
//!    registered object missing from the fixture fails, and an object
//!    (or non-prose field) added to the fixture but unregistered fails
//!    the name-set walk — nothing is pinned by silence.
//! 2. **The SDK codec reproduces each pinned object exactly.** The
//!    pinned bytes decode through `from_bytes` into the fields the
//!    fixture names, re-encode byte-identically through `to_bytes`,
//!    encode from the fixture's field values back to the pinned bytes,
//!    and `JoinRequest::create`'s deterministic Ed25519 signer
//!    reproduces the pinned signature over the pinned challenge.
//! 3. **A positive control**: the identity derivation and non-empty
//!    byte counts below fail on an empty, unreadable, or truncated
//!    fixture, so a green parity run cannot be a harness that read
//!    nothing.
//!
//! The SDK packages no second copy of the fixture (unlike the leaf's
//! `test_vectors` constants, whose wasm target needs an in-package
//! copy), so there is no package/repository mirror to keep in step and
//! nothing exempted here: a missing repository fixture is a fail.

use std::path::PathBuf;

use net_sdk::enrollment::{reject, InviteToken, JoinError, JoinOutcome, JoinRequest};
use net_sdk::identity::EntityId;
use net_sdk::{Identity, ENROLLMENT_SERVICE};

/// Every fixture object this witness pins. Set-equality with the
/// fixture's non-prose top-level names below, so an object added to
/// the fixture but never asserted here fails — the one-directional
/// gap MR#126 names — and an object the registry names but the
/// fixture lacks fails too (no silent skips).
const REGISTRY: [&str; 4] = ["identity", "invite", "join_request", "join_outcome"];

/// The pinned field under each registered object. Both directions are
/// walked: a registered field absent from the fixture fails, and a
/// non-prose fixture field absent from this registry fails (a field
/// nothing asserts can drift silently, at field granularity).
const PINNED_FIELDS: [(&str, &[&str]); 4] = [
    ("identity", &["entity_secret_hex", "device_entity_id"]),
    (
        "invite",
        &["root", "nonce", "expires_at", "rendezvous", "invite_hex"],
    ),
    (
        "join_request",
        &[
            "service",
            "name",
            "tags",
            "max_body_bytes",
            "join_request_hex",
        ],
    ),
    (
        "join_outcome",
        &[
            "admitted_hex",
            "admitted_chain_utf8",
            "rejected_hex",
            "rejected_code",
            "rejected_code_name",
            "rejected_message_utf8",
        ],
    ),
];

/// The shared cross-language golden vector, read from the repository
/// copy the Go / TypeScript / Python consumers read. The SDK packages
/// no mirror of it, so this is the one copy — absent is a fail, never
/// a skip.
fn fixture() -> serde_json::Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/cross_lang_wire")
        .join("enroll_exchange.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "the shared fixture must be readable at {}: {e}",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("the fixture parses")
}

fn field<'a>(document: &'a serde_json::Value, pointer: &str) -> &'a str {
    document
        .pointer(pointer)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("fixture has no {pointer}"))
}

fn number(document: &serde_json::Value, pointer: &str) -> u64 {
    document
        .pointer(pointer)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| panic!("fixture has no number at {pointer}"))
}

fn strings(document: &serde_json::Value, pointer: &str) -> Vec<String> {
    document
        .pointer(pointer)
        .and_then(serde_json::Value::as_array)
        .unwrap_or_else(|| panic!("fixture has no array at {pointer}"))
        .iter()
        .map(|entry| {
            entry
                .as_str()
                .unwrap_or_else(|| panic!("{pointer} has a non-string entry"))
                .to_string()
        })
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex digit"))
        .collect()
}

fn unhex_array<const N: usize>(s: &str) -> [u8; N] {
    unhex(s)
        .try_into()
        .unwrap_or_else(|v: Vec<u8>| panic!("hex must decode to {N} bytes, got {}", v.len()))
}

/// The fixture's `rejected_code_name` vocabulary resolved through the
/// SDK's stable [`reject`] codes, so the named code and the numeric
/// code are pinned to each other through production constants.
fn reject_code_named(name: &str) -> Option<u16> {
    Some(match name {
        "malformed" => reject::MALFORMED,
        "unknown_invite" => reject::UNKNOWN_INVITE,
        "expired" => reject::EXPIRED,
        "bad_request" => reject::BAD_REQUEST,
        "replay" => reject::REPLAY,
        "internal" => reject::INTERNAL,
        "denied" => reject::DENIED,
        "unrenewable" => reject::UNRENEWABLE,
        _ => return None,
    })
}

/// Every fixture object the registry names is asserted, and the
/// fixture names nothing else.
///
/// The parity witness walks [`REGISTRY`]; a vector (or field) added to
/// the fixture but never registered is invisible to such a walk —
/// exactly the defect `leaf/tests/fixture_parity.rs`'s directory walk
/// exists for — so the fixture's own names are walked back against the
/// registry at both object and field granularity.
#[test]
fn every_fixture_object_the_registry_names_is_asserted() {
    let document = fixture();
    let object = document.as_object().expect("the fixture is a JSON object");

    // Object level: exactly the registered names plus the prose
    // `description`. A registered name missing here is a silent skip;
    // an unregistered name pins nothing.
    let mut present: Vec<&str> = object
        .keys()
        .map(String::as_str)
        .filter(|name| *name != "description")
        .collect();
    present.sort();
    let mut registered: Vec<&str> = REGISTRY.to_vec();
    registered.sort();
    assert_eq!(
        present, registered,
        "the fixture's objects and the REGISTRY disagree — a missing name \
         skips an object silently and an unregistered name pins nothing"
    );

    // Field level, both directions. `note` is prose the fixture marks
    // as such; everything else must be registered and pinned.
    for object_name in REGISTRY {
        let (object_name, fields) = PINNED_FIELDS
            .iter()
            .find(|(name, _)| *name == object_name)
            .expect("every REGISTRY name has a PINNED_FIELDS entry");
        for field_name in *fields {
            let pointer = format!("/{object_name}/{field_name}");
            let value = document.pointer(&pointer).unwrap_or_else(|| {
                panic!("fixture has no {pointer} — no registered field may be missing")
            });
            // Non-vacuity at field level: a registered field must pin
            // real text, a real count, or a real list — never empty.
            match value {
                serde_json::Value::String(s) => {
                    assert!(!s.is_empty(), "{pointer} must pin non-empty text or bytes")
                }
                serde_json::Value::Number(n) => {
                    assert!(n.as_u64().is_some(), "{pointer} must pin a count")
                }
                serde_json::Value::Array(items) => {
                    assert!(!items.is_empty(), "{pointer} must pin at least one entry")
                }
                other => panic!("{pointer} pins neither text, a count, nor a list: {other}"),
            }
        }
        let pinned: std::collections::BTreeSet<&str> = fields.iter().copied().collect();
        let extra: Vec<&str> = object[*object_name]
            .as_object()
            .expect("registered name is an object")
            .keys()
            .map(String::as_str)
            .filter(|key| *key != "note" && !pinned.contains(key))
            .collect();
        assert!(
            extra.is_empty(),
            "/{object_name} carries unregistered field(s) {extra:?} — a field \
             no test asserts can drift silently"
        );
    }
}

/// The SDK enrollment codec reproduces the pinned objects exactly.
///
/// Both directions per object: the pinned bytes decode through the
/// production `from_bytes` into the fields the fixture names and
/// re-encode byte-identically, and the fixture's field values encode
/// through the production `to_bytes` back to the pinned bytes. For the
/// signed request the pin is stronger than round-tripping: RFC 8032
/// Ed25519 is deterministic, so `JoinRequest::create` must reproduce
/// the leaf-generated signature byte for byte over the domain-
/// separated challenge.
#[test]
fn the_sdk_enrollment_codec_reproduces_the_pinned_objects() {
    let document = fixture();
    let mut asserted = 0;

    // The fixture names the identity it was generated from; assert the
    // derivation rather than trusting the note.
    let identity = Identity::from_seed(unhex_array::<32>(field(
        &document,
        "/identity/entity_secret_hex",
    )));
    assert_eq!(
        hex(identity.entity_id().as_bytes()),
        field(&document, "/identity/device_entity_id"),
        "the fixture's device_entity_id must be the SDK's derivation of the \
         secret it names"
    );
    asserted += 1;

    // Invite: decode accepts the pinned bytes (the fixture description's
    // named half of the pin), the fields match, and both directions
    // re-encode to the pinned bytes.
    let pinned_invite = unhex(field(&document, "/invite/invite_hex"));
    let invite = InviteToken::from_bytes(&pinned_invite).expect(
        "InviteToken::from_bytes accepts invite_hex — the fixture's \
         description names this half of the pin",
    );
    assert_eq!(
        hex(invite.root.as_bytes()),
        field(&document, "/invite/root"),
        "the pinned invite's root must be the fixture's"
    );
    assert_eq!(
        hex(&invite.nonce),
        field(&document, "/invite/nonce"),
        "the pinned invite's nonce must be the fixture's"
    );
    assert_eq!(
        invite.expires_at,
        number(&document, "/invite/expires_at"),
        "the pinned invite's expiry must be the fixture's"
    );
    assert_eq!(
        invite.rendezvous,
        field(&document, "/invite/rendezvous"),
        "the rendezvous must survive the length-prefixed round trip"
    );
    assert_eq!(
        invite.to_bytes(),
        pinned_invite,
        "the pinned invite bytes must survive the SDK's canonical re-encode"
    );
    let built_invite = InviteToken {
        root: EntityId::from_bytes(unhex_array::<32>(field(&document, "/invite/root"))),
        rendezvous: field(&document, "/invite/rendezvous").to_string(),
        nonce: unhex_array::<16>(field(&document, "/invite/nonce")),
        expires_at: number(&document, "/invite/expires_at"),
    };
    assert_eq!(
        hex(&built_invite.to_bytes()),
        field(&document, "/invite/invite_hex"),
        "the SDK's InviteToken encoder drifted from the pinned invite bytes"
    );
    asserted += 1;

    // Join request: the fixture description's other named half —
    // from_bytes accepts and verify_self_signature passes — plus field
    // parity, re-encode parity, and the deterministic signer
    // reproducing the pinned signature.
    let pinned_request = unhex(field(&document, "/join_request/join_request_hex"));
    let request = JoinRequest::from_bytes(&pinned_request).expect(
        "JoinRequest::from_bytes accepts join_request_hex — the fixture's \
         description names this half of the pin",
    );
    request.verify_self_signature().expect(
        "verify_self_signature() passes over the pinned request — the SDK's \
         challenge reconstruction must match the signer's, as the anchor's \
         provider requires before it admits anyone",
    );
    assert_eq!(
        hex(request.device.as_bytes()),
        field(&document, "/identity/device_entity_id"),
        "the pinned request's device must be the fixture identity's"
    );
    assert_eq!(
        request.name,
        field(&document, "/join_request/name"),
        "the pinned request's name must be the fixture's"
    );
    let tags = strings(&document, "/join_request/tags");
    assert_eq!(
        request.tags, tags,
        "the pinned request's tags must be the fixture's, in order"
    );
    assert_eq!(
        hex(&request.invite_nonce),
        field(&document, "/invite/nonce"),
        "the pinned request must echo the invite nonce as proof-of-invite"
    );
    assert_eq!(
        hex(request.root.as_bytes()),
        field(&document, "/invite/root"),
        "the pinned request must bind to the invited mesh root"
    );
    assert_eq!(
        request.to_bytes(),
        pinned_request,
        "the pinned request bytes must survive the SDK's canonical re-encode"
    );
    // Envelope metadata, pinned to production surfaces.
    assert_eq!(
        field(&document, "/join_request/service"),
        ENROLLMENT_SERVICE,
        "the pinned request rides the enrollment nRPC service the SDK serves"
    );
    let max_body_bytes = number(&document, "/join_request/max_body_bytes");
    assert!(
        pinned_request.len() as u64 <= max_body_bytes,
        "the pinned request must fit the body bound the fixture names \
         ({max_body_bytes}) — over it §12's admission refuses"
    );
    let rebuilt = JoinRequest::create(
        &identity,
        field(&document, "/join_request/name"),
        tags,
        &built_invite,
    );
    assert_eq!(
        hex(&rebuilt.to_bytes()),
        field(&document, "/join_request/join_request_hex"),
        "the SDK's JoinRequest signer drifted from the pinned request — \
         Ed25519 is deterministic, so create() must reproduce the \
         leaf-generated signature byte for byte"
    );
    asserted += 1;

    // Join outcomes: both pinned shapes, both directions. `into_chain`
    // is not called on the admitted shape — the fixture's chain is
    // placeholder bytes ("chain-bytes"), not a serialized
    // DelegationChain; the wire shape is what is pinned here.
    let admitted_chain = field(&document, "/join_outcome/admitted_chain_utf8")
        .as_bytes()
        .to_vec();
    let admitted = JoinOutcome::from_bytes(&unhex(field(&document, "/join_outcome/admitted_hex")))
        .expect("the SDK's JoinOutcome decoder accepts admitted_hex");
    assert_eq!(
        admitted,
        JoinOutcome::Admitted {
            chain: admitted_chain.clone()
        },
        "the pinned admitted outcome must decode to the chain the fixture names"
    );
    assert_eq!(
        admitted.to_bytes(),
        unhex(field(&document, "/join_outcome/admitted_hex")),
        "the pinned admitted outcome must survive the SDK's canonical re-encode"
    );
    assert_eq!(
        hex(&JoinOutcome::Admitted {
            chain: admitted_chain
        }
        .to_bytes()),
        field(&document, "/join_outcome/admitted_hex"),
        "the SDK's JoinOutcome encoder drifted from the pinned admitted shape"
    );

    let code = number(&document, "/join_outcome/rejected_code") as u16;
    let message = field(&document, "/join_outcome/rejected_message_utf8");
    let rejected_bytes = unhex(field(&document, "/join_outcome/rejected_hex"));
    let rejected = JoinOutcome::from_bytes(&rejected_bytes)
        .expect("the SDK's JoinOutcome decoder accepts rejected_hex");
    assert_eq!(
        rejected,
        JoinOutcome::Rejected {
            code,
            message: message.to_string()
        },
        "the pinned rejected outcome must decode to the code and message the \
         fixture names"
    );
    assert_eq!(
        rejected.to_bytes(),
        rejected_bytes,
        "the pinned rejected outcome must survive the SDK's canonical re-encode"
    );
    assert_eq!(
        hex(&JoinOutcome::Rejected {
            code,
            message: message.to_string()
        }
        .to_bytes()),
        field(&document, "/join_outcome/rejected_hex"),
        "the SDK's JoinOutcome encoder drifted from the pinned rejected shape"
    );
    assert_eq!(
        code,
        reject_code_named(field(&document, "/join_outcome/rejected_code_name"))
            .expect("rejected_code_name is one of the SDK's stable reject codes"),
        "rejected_code must be the SDK's stable code for rejected_code_name"
    );
    // Device-side interpretation: tag 1 must leave the session
    // provisional and surface the operator's code and message —
    // the same bytes a device feeds to into_chain.
    let err = JoinOutcome::from_bytes(&rejected_bytes)
        .expect("decode")
        .into_chain(identity.entity_id(), &invite.root)
        .expect_err("tag 1 must leave the session provisional");
    match err {
        JoinError::Rejected {
            code: err_code,
            message: err_message,
        } => {
            assert_eq!(err_code, code, "the refusal's code must survive");
            assert_eq!(err_message, message, "the operator's message must survive");
        }
        other => panic!("the pinned rejection must surface as JoinError::Rejected: {other}"),
    }
    asserted += 1;

    assert_eq!(
        asserted,
        REGISTRY.len(),
        "every object the registry names must have been asserted above — a \
         REGISTRY name without an assertion block is the one-directional gap \
         MR#126 names"
    );
}

/// Positive control for the parity witness: this harness reads the
/// real pinned vector.
///
/// The named identity derives the pinned device id through the SDK,
/// every pinned byte string decodes to non-empty bytes, and the object
/// count is exactly the registry's plus the description — assertions
/// that all fail on an empty, unreadable, or truncated fixture. A
/// parity run is only meaningful beside this control: it is what
/// separates "the codec reproduces the fixture" from "the harness read
/// nothing and compared nothing".
#[test]
fn the_harness_reads_the_real_pinned_vector() {
    let document = fixture();
    let object = document.as_object().expect("the fixture is a JSON object");
    assert_eq!(
        object.len(),
        REGISTRY.len() + 1,
        "the fixture must carry exactly the registered objects plus its \
         description ({REGISTRY:?})"
    );

    let identity = Identity::from_seed(unhex_array::<32>(field(
        &document,
        "/identity/entity_secret_hex",
    )));
    assert_eq!(
        hex(identity.entity_id().as_bytes()),
        field(&document, "/identity/device_entity_id"),
        "the named secret must derive the pinned device id through the SDK — \
         the identity control that fails on an empty or wrong read"
    );

    for pointer in [
        "/invite/invite_hex",
        "/join_request/join_request_hex",
        "/join_outcome/admitted_hex",
        "/join_outcome/rejected_hex",
    ] {
        let bytes = unhex(field(&document, pointer));
        assert!(
            !bytes.is_empty(),
            "{pointer} must pin non-empty bytes — empty pinned bytes would \
             make any round trip vacuously green"
        );
    }
}
