/*
 * mcp_cases.h — GENERATED by .github/scripts/gen-c-fixture-cases.py
 * from the JSON fixtures in net/crates/net/tests/cross_lang_mcp/. Do not
 * edit; CI regenerates it and fails on any difference.
 *
 * The cases every binding runs against the MCP bridge helpers and the
 * consent gate, as C data for examples/c/mcp.c. A decision case's ops
 * are `<op> <cap_id>` pairs separated by `;`.
 */

#ifndef CU_MCP_CASES_H
#define CU_MCP_CASES_H

typedef struct { const char* name; const char* program; const char* args; const char* envs; const char* override_; int force; const char* expected; } cu_classify_case;
typedef struct { const char* name; const char* tool; const char* server_version; const char* credential_status; const char* substitutability; const char* tool_id; const char* mcp_name; const char* bridge_metadata; } cu_lower_case;
typedef struct { const char* name; const char* input; const char* expected; } cu_canon_case;
typedef struct { const char* name; const char* input; } cu_invalid_case;
typedef struct { const char* name; const char* status; int expected; } cu_requires_case;
typedef struct { const char* name; const char* ops; const char* cap_id; const char* credential_status; const char* expected; } cu_decision_case;

static const cu_classify_case cu_classify_cases[] = {
    {"secret_shaped_env_is_credentialed", "npx", "[\"-y\",\"some-server\"]", "{\"GITHUB_TOKEN\":\"ghp_must_never_cross\"}", NULL, 0, "credentialed"},
    {"known_external_api_is_external_api", "npx", "[\"-y\",\"@modelcontextprotocol/server-github\"]", "{}", NULL, 0, "external_api"},
    {"unrecognized_is_unknown_and_still_gated", "uvx", "[\"mcp-server-time\"]", "{\"TZ\":\"UTC\"}", NULL, 0, "unknown"},
    {"forced_downgrade_is_none", "uvx", "[\"mcp-server-time\"]", "{}", "no-credentials", 1, "none"},
    {"upward_override_is_credentialed", "uvx", "[\"mcp-server-time\"]", "{}", "credentialed", 0, "credentialed"},
};
#define CU_CLASSIFY_CASES_N (sizeof cu_classify_cases / sizeof cu_classify_cases[0])

static const cu_lower_case cu_lower_cases[] = {
    {"echo_credentialed_provider_local", "{\"name\":\"echo\",\"description\":\"echo it back\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"message\":{\"type\":\"string\"}}}}", "2.0.0", "credentialed", "provider_local", "echo", "echo", "\"tool::echo::compat_tier\":\"mcp_bridge\"\012\"tool::echo::credential_status\":\"credentialed\"\012\"tool::echo::invocation_scope\":\"same_root_identity\"\012\"tool::echo::substitutability\":\"provider_local\"\012\"tool::echo::visibility\":\"owner_only\""},
    {"add_none_provider_equivalent", "{\"name\":\"add\",\"description\":\"add two numbers\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"a\":{\"type\":\"number\"},\"b\":{\"type\":\"number\"}},\"required\":[\"a\",\"b\"]}}", "1.4.0", "none", "provider_equivalent", "add", "add", "\"tool::add::compat_tier\":\"mcp_bridge\"\012\"tool::add::credential_status\":\"none\"\012\"tool::add::invocation_scope\":\"same_root_identity\"\012\"tool::add::substitutability\":\"provider_equivalent\"\012\"tool::add::visibility\":\"owner_only\""},
};
#define CU_LOWER_CASES_N (sizeof cu_lower_cases / sizeof cu_lower_cases[0])

static const cu_canon_case cu_canon_cases[] = {
    {"plain_decimal", "42/echo", "42/echo"},
    {"hex_lower", "0x2a/echo", "42/echo"},
    {"hex_upper", "0X2A/echo", "42/echo"},
    {"leading_space", " 42/echo", "42/echo"},
    {"trailing_space_in_provider", "42 /echo", "42/echo"},
    {"nested_capability_hex_provider", "0x10/svc/sub", "16/svc/sub"},
    {"non_numeric_provider_trimmed", " nodeb /echo", "nodeb/echo"},
    {"named_provider", "homelab/github.create_issue", "homelab/github.create_issue"},
};
#define CU_CANON_CASES_N (sizeof cu_canon_cases / sizeof cu_canon_cases[0])

static const cu_invalid_case cu_invalid_cases[] = {
    {"missing_slash", "bareword"},
    {"empty_provider", "/cap"},
    {"empty_capability", "prov/"},
};
#define CU_INVALID_CASES_N (sizeof cu_invalid_cases / sizeof cu_invalid_cases[0])

static const cu_requires_case cu_requires_cases[] = {
    {"none_is_gated_not_trusted", "none", 1},
    {"credentialed", "credentialed", 1},
    {"external_api", "external_api", 1},
    {"unknown", "unknown", 1},
    {"empty", "", 1},
    {"unrecognized", "bogus", 1},
};
#define CU_REQUIRES_CASES_N (sizeof cu_requires_cases / sizeof cu_requires_cases[0])

static const cu_decision_case cu_decision_cases[] = {
    {"empty_policy_gates_everything", "", "b/echo", "none", "requires_approval"},
    {"allow_admits", "allow b/echo", "b/echo", "credentialed", "allowed"},
    {"allow_is_specific", "allow b/echo", "b/other", "credentialed", "requires_approval"},
    {"pin_admits", "pin b/slack.post", "b/slack.post", "external_api", "allowed"},
    {"pin_hex_admits_decimal", "pin 0x2a/echo", "42/echo", "external_api", "allowed"},
    {"unpin_re_gates", "pin b/x;unpin b/x", "b/x", "credentialed", "requires_approval"},
};
#define CU_DECISION_CASES_N (sizeof cu_decision_cases / sizeof cu_decision_cases[0])

#endif /* CU_MCP_CASES_H */
